---
title: "more_than_2_countries"
author: "KH"
date: "9 3 2021"
output: html_document
---
```{r}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(installr)
library(dplyr)
library(tidyr)
library(reshape2)
library(R0)
library(ggpubr)
library(ggpmisc)
library(COVID19)
```

```{r, import data from COVID19 Datahub}

y <- covid19(c("United Kingdom", "Czech Republic", "United States"))
verbose = FALSE
```

```{r}
#Data Prep

y <- y %>% mutate(active_cases = confirmed - recovered - deaths)
y <- y %>% mutate(roll_avg = zoo::rollmean(active_cases, k = 7, 
                                           fill = NA, align = "right"))

y <- y %>% mutate(growth_active_cases = active_cases - lag(active_cases, n=1L))
y <- y %>% mutate(roll_growth_active_cases = zoo::rollmean(growth_active_cases, k = 7, 
                                                    fill = NA, align = "right"))

y <- y %>% mutate(roll_new_cases = zoo::rollmean((confirmed - lag(confirmed, n=1L)),
                  k = 7, fill = NA, align = "right"))

y <- y %>% mutate(new_cases = (confirmed - lag(confirmed, n = 1L)))

y <- y %>% mutate(seven_days_cases = zoo::rollsum(new_cases, k = 7, fill = NA, align = "right"))

y <- y %>% mutate(incidence_week = (seven_days_cases /(population * 10^-5)))

y <- y %>% mutate(new_deaths = (deaths - lag(deaths, n=1L)))

y <- y %>% mutate(seven_days_deaths = zoo::rollsum(new_deaths, k = 7, fill = NA, align = "right"))

y <- y %>% mutate(new_deaths_incidence = (seven_days_deaths /(population * 10^-5)))

y <- y %>% mutate(vaccinated_perc = (vaccines / population)*100)

y <- y %>% dplyr::select(new_cases, active_cases, roll_avg, roll_growth_active_cases, growth_active_cases, roll_new_cases, seven_days_cases, incidence_week, new_deaths, seven_days_deaths, vaccinated_perc, new_deaths_incidence, everything())


AUT <- filter(y, id == "AUT")
CZE <- filter(y, id == "CZE")
GBR <- filter(y, id == "GBR")
```

```{r}
#Incidence / week progression

p1 <- ggplot(data=y)+
  geom_point(aes(x = (date), y=incidence_week, colour= id))+
  #theme(axis.text.x=element_text(angle=90, vjust=0.5))+
  xlim(as.Date("2021-01-01"), NA)+
  ylab("Weekly Incidence per 100k")+
  xlab("Date")+
  labs(title = "Weekly incidence per 100k", colour = "Country")+
  theme(plot.title = element_text(hjust = 0.5))



```



```{r}
#Vaccination percentage

p2 <- ggplot(data = y)+
  geom_point(aes(x=(date), y=vaccinated_perc, colour = id))+
  xlim(as.Date("2021-01-01"), NA)+
  labs(title= "Vaccinations in % of capita", colour = "Country")+
  ylab("Total vaccinations / population in %")+
  xlab("Date")+
  theme(plot.title = element_text(hjust = 0.5))
```


```{r}
#New Deaths per Week


p3 <- ggplot(data = y,aes(x=(date), y=seven_days_deaths, fill=id))+
  geom_bar(stat = "identity", position=position_dodge())+
  xlim(as.Date("2021-01-01"), NA)+
  labs(title= "Weekly new deaths", fill = "Country")+
  ylab("Weekly new deaths")+
  xlab("Date")+
  theme(plot.title = element_text(hjust = 0.5))
```

```{r}
#New Deaths Incidence per week and 100k

p4 <- ggplot(data = y)+
  geom_point(aes(x=(date), y=new_deaths_incidence, colour = id))+
  xlim(as.Date("2021-01-01"), NA)+
  labs(title= "New Deaths per Week and 100k", colour = "Country")+
  ylab("Weekly new deaths per 100k")+
  xlab("Date")+
  theme(plot.title = element_text(hjust = 0.5))
```


```{r}
#Aggregated Plot 1

gridExtra::grid.arrange(p1, p2, p3, ncol = 1)
```
```{r}
#Aggregated Plot 2

gridExtra::grid.arrange(p1, p2, p4, ncol = 1)
```
